image: python:3.5  # no wxPython wheel for 3.6

pages:
  script:
  - apt-get install make
  - python3 -m ensurepip
  - pip3 install sphinx
  - pip3 install https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-14.04/wxPython-4.0.0b1-cp35-cp35m-linux_x86_64.whl
  - pip3 install .  # install psychopy so that reference can be found
  - cd docs
  - make html
  - cd ..
  - mv docs/build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
