# vim ft=yaml
# travis-ci.org and coveralls definition for PsychoPy tests
dist: precise  # the default (trusty) causing problem with SSL as of Aug 2017
sudo: true

language: python

python:
  - "2.7"

env:
  global: DISPLAY=:99.0

virtualenv:
  system_site_packages: true

before_install:
  # System setup
  - travis_retry sudo apt-get update -qq
  - travis_retry sudo apt-get install -qq lsb-release
  - source /etc/lsb-release
  - echo ${DISTRIB_CODENAME}
  - wget -O- http://neuro.debian.net/lists/${DISTRIB_CODENAME}.us-nh.full | sudo tee /etc/apt/sources.list.d/neurodebian.sources.list
  - wget -q -O- http://neuro.debian.net/_static/neuro.debian.net.asc | sudo apt-key add -
  - travis_retry sudo apt-get update -qq
  - sudo apt-cache policy  # What is actually available?

  - travis_retry sudo apt-get install -qq xvfb xauth libgl1-mesa-dri libavbin0
  - travis_retry sudo apt-get install -qq flac
  - flac -version

  # Locales
  # - travis_retry sudo apt-get install -qq language-pack-en-base  # English locales
  - travis_retry sudo apt-get install -qq language-pack-ja-base  # Japanese locale
  # - sudo dpkg-reconfigure locales
  # - locale -a  # list available locales

  # APT Python dependencies for PsychoPy
  - echo "Installing PsychoPy dependencies via apt..."
  - travis_retry sudo apt-get install -qq python-xlib python-pygame python-opengl
  - travis_retry sudo apt-get install -qq python-numpy python-scipy python-matplotlib python-pandas
  - travis_retry sudo apt-get install -qq python-yaml python-lxml python-configobj python-openpyxl
  - travis_retry sudo apt-get install -qq python-imaging python-mock
  - travis_retry sudo apt-get install -qq python-qt4 python-wxgtk2.8
  - travis_retry sudo apt-get install -qq python-pyo python-opencv
  - travis_retry sudo apt-get install -qq python-mock

  # PIP dependencies for PsychoPy
  - echo "Installing PsychoPy dependencies via pip..."
  - travis_retry sudo pip install --upgrade -force-reinstall -qq pip
  - travis_retry sudo pip install --upgrade -force-reinstall -qq -r requirements_travis.txt
  - python -c 'import pyglet; print pyglet.version'

install:
  - python setup.py build
  - python setup.py install

before_script:
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1024x768x24 -ac +extension GLX +render -noreset;
    fi;

script:
  - pytest --cov-config .travis_coveragerc --cov=psychopy -v -s -m "not needs_sound" psychopy

after_success:
  - coveralls
  - codecov
