name: conda-py3.6
channels:
- conda-forge
dependencies:
- python=3.6
- arabic_reshaper
- astunparse
- backports
- codecov
- coveralls
- esprima-python
- gitpython
- ffmpeg
- freetype-py
- future
- gevent
- greenlet
- imageio
- imageio-ffmpeg
- json_tricks
- lxml
- matplotlib
- moviepy
- msgpack-numpy
- msgpack-python
- numpy
- opencv
- openpyxl
- pandas
- pillow
- pip!=19.0,!=19.0.1,!=19.0.2
- psutil
- pyglet>=1.3
- pyopengl
- pyosf
- pyqt
- pyserial
- pysoundfile
- pytables
- pytest<4.1
- pytest-cov
- python-bidi
- python-gitlab
- python-sounddevice
- pyyaml
- pyzmq
- requests
- scipy
- wheel
- wxpython!=4.0.2,!=4.0.3
- xlrd
- pip:
  - pygame
  - pyparallel
