name: anaconda-py2.7
channels:
- conda-forge
- defaults
dependencies:
- python=2.7
- astunparse
- backports
- bzip2
- cffi
- codecov
- coveralls
- gitpython
- ffmpeg
- freetype
- future
- gevent
- greenlet
- json_tricks
- libffi
- libflac
- lxml
- matplotlib
- moviepy
- msgpack-python
- numexpr
- numpy
- opencv
- openpyxl
- pandas
- pillow
- pip
- pixman
- prompt_toolkit
- psutil
- pycparser
- pygments
- pyopengl
- pyopenssl
- pyosf
- pyqt
- pyserial
- pysoundfile
- python-bidi
- pyyaml
- pyzmq
- requests
- scipy
- setuptools
- sip
- six
- pyglet>=1.3
- pytables
- urllib3
- wheel
- xlrd
- xz
- yaml
- lzo
- pytables
- pytest<4.1
- pytest-cov
- python-sounddevice
- wxpython!=4.0.2,!=4.0.3
- zlib
- pip:
  - arabic_reshaper
  - esprima
  - et-xmlfile
  - freetype-py
  - prompt-toolkit
  - pygame
  - pyparallel
  - python-gitlab
