name: anaconda-py3.6
channels:
- conda-forge
- defaults
dependencies:
- python=3.6
- astunparse
- backports
- bzip2
- cffi
- codecov
- coveralls
- gitpython
- ffmpeg
- freetype
- future
- gevent
- greenlet
- hdf5
- json_tricks
- libflac
- lxml
- matplotlib
- moviepy
- msgpack-python
- numexpr
- numpy
- opencv
- openpyxl
- pandas
- pillow
- pip
- psutil
- pyopengl
- pyosf
- pyqt
- pyserial
- pysoundfile
- pytest
- pytest-cov
- python-bidi
- python-sounddevice
- pyyaml
- pyzmq
- requests
- scipy
- setuptools
- sip
- six
- pyglet>=1.3
- pytables
- urllib3
- wheel
- x264
- xlrd
- xz
- yaml
- lzo
- pytables
- wxpython!=4.0.2,!=4.0.3
- zlib
- pip:
  - arabic_reshaper
  - esprima
  - freetype-py
  - pygame
  - pyparallel
  - python-gitlab
